baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hotel Theme"

# Основні параметри сайту

[params]
description = "A modular Hugo theme example"
keywords = "Some keywords"
main_color = "#ffffff"
header_and_footer_color = "#b1b1b1"
header_and_footer_text = "#ffffff"
text_color = "#333333"
accent_color = "#007bff"
hover_color = "#0056b3"

# Налаштування компонентів
[params.layouts]
footer = "footer-1"
header = "header-3"
hero = "hero-3"

# Доступні компоненти
[params.layouts.available]
headers = ["header-1", "header-2", "header-3"]
footers = ["footer-1", "footer-2", "footer-3"]
heros = ["hero-1", "hero-2", "hero-3"]

# Налаштування hero секції
[params.hero]
title = "Welcome to Our Luxury Hotel"
description = "Discover a world of luxury and relaxation at our hotel. We offer exceptional service, stunning views, and unforgettable experiences."
background_image = "/images/hero-bg.jpg"
overlay_opacity = 0.5

# Керування секціями
[params.sections]
hero = true

# Налаштування футера
[params.footer]
terms_url = "/terms"
terms_text = "Terms & Conditions"
privacy_url = "/privacy"
privacy_text = "Privacy Policy"
copyright_text = "All rights reserved."

# Налаштування контактної форми
[params.contact]
title = "Get in Touch"
name_placeholder = "Your Name"
email_placeholder = "Your Email"
message_placeholder = "Your Message"
submit_text = "Send Message"
form_action = "/contact"

[params.social]
twitter = "https://twitter.com/"
facebook = "https://facebook.com/"
instagram = "https://instagram.com/"
youtube = "https://youtube.com/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3
