baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hotel Theme"

[taxonomies]

# Основні параметри сайту
[params]
  description = "A modular Hugo theme example"
  keywords = "Some keywords"
  main_color = "#ffffff"
  header_and_footer_color = "#1b1b1b"
  header_and_footer_text = "#fff"
  text_color = "#fff"
  accent_color = "tomato"
  hover_color = "tomato"

# Керування секціями
[params.sections]
  hero = true
  offers = true
  mission = true
  choose = true
  team = true
  commitment = true

# Налаштування соціальних мереж
[params.social]
  twitter = "https://twitter.com/"
  facebook = "https://facebook.com/"
  instagram = "https://instagram.com/"
  youtube = "https://youtube.com/"


# Налаштування контактної форми
[params.contact]
  title = "Get in Touch"
  name_placeholder = "Your Name"
  email_placeholder = "Your Email"
  message_placeholder = "Your Message"
  submit_text = "Send Message"
  form_action = "/"

# Налаштування сторінок
[params.pages]
  # Домашня сторінка
  [params.pages.home.hero]
    hero_title = "Заголовок для домашньої сторінки"
    hero_subtitle = "Підзаголовок для домашньохї сторінки"
    hero_description = "Якийсь там бла-бла-бла опис домашньої сторінки"

  [params.pages.home.offers]
    offers_title = "What We Offer"
    offers_subtitle = "Experience Luxury and Comfort"

  # Сторінка Про нас
  [params.pages.about]
    [params.pages.about.hero]
      hero_title = "Заголовок для сторінки про нас"
      hero_subtitle = "Підзаголовок для сторінки про нас"
      hero_description = "Якийсь там бла-бла-бла опис для сторінки про нас"

  # Сторінка контактів
  [params.pages.contact]
    [params.pages.contact.hero]
      hero_title = "Заголовк для сторінки контактів"
      hero_subtitle = "Підзаголовок для сторінки контактів"
      hero_description = "Якийсь там бла-бла-бла опис для сторінки контактів"


# Налаштування секції "What we offer" на головній сторінці (можна додавати більше - іконки з бутстрапа\вебфонтс)
[params.offers]
  [[params.offers.items]]
    icon = "fas fa-bed"
    title = "Luxury Rooms"
    description = "Experience ultimate comfort in our elegantly appointed rooms with premium amenities and stunning views."

  [[params.offers.items]]
    icon = "fas fa-utensils"
    title = "Fine Dining"
    description = "Savor exquisite cuisine prepared by world-class chefs in our restaurants and cafes."

  [[params.offers.items]]
    icon = "fas fa-spa"
    title = "Spa & Wellness"
    description = "Rejuvenate your body and mind with our comprehensive spa treatments and wellness programs."

# Додавання нових параметрів
[params.mission]
  title = "Our Mission"
  subtitle = "Excellence in Hospitality"
  description = "We strive to provide exceptional service and unforgettable experiences to our guests"
  image = "/images/mission.webp"

[params.choose]
  title = "Why Choose Us"
  subtitle = "Experience the Difference"
  description = "Discover what makes our hotel the perfect choice for your stay"

  [[params.choose.items]]
    icon = "fas fa-star"
    title = "Luxury Comfort"
    description = "Experience ultimate comfort in our elegantly appointed rooms"

  [[params.choose.items]]
    icon = "fas fa-map-marker-alt"
    title = "Prime Location"
    description = "Located in the heart of the city with easy access to attractions"

  [[params.choose.items]]
    icon = "fas fa-concierge-bell"
    title = "Exceptional Service"
    description = "Our dedicated staff ensures your stay is nothing short of perfect"


[params.team]
  title = "Our Team"
  subtitle = "Meet the People Behind Our Success"
  description = "Our experienced team is dedicated to providing you with the best service"

  [[params.team.members]]
    name = "John Doe"
    position = "General Manager"
    image = "/images/team/john.jpg"

  [[params.team.members]]
    name = "Jane Smith"
    position = "Head Chef"
    image = "/images/team/jane.jpg"

  [[params.team.members]]
    name = "Mike Johnson"
    position = "Guest Relations Manager"
    image = "/images/team/mike.jpg"


[params.commitment]
  title = "Our Commitment"
  description = "We are committed to providing you with the best possible experience"
  email = "info@luxuryhotel.com"

# Готелі
[params.hotels]
  # Конкертний готель
  [[params.hotels.list]]
    title = "Example hotel"
    type = "example-hotels"
    image = "/images/spa.jpg"

    [[params.hotels.list.description]]
      subtitle = "Welcome to Relax SPA"
      text = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. It has been the industry's standard dummy text ever since the 1500s."

    [[params.hotels.list.description]]
      subtitle = "Why Choose Us?"
      text = "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."

    [[params.hotels.list.description]]
      subtitle = "Modern Comfort"
      text = "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text."


# Налаштування футера
[params.footer]
  terms_url = "/terms"
  terms_text = "Terms & Conditions"
  privacy_url = "/privacy"
  privacy_text = "Privacy Policy"
  copyright_text = "All rights reserved."

# Налаштування компонентів
[params.layouts]
  footer = "footer-1"
  header = "header-3"
  hero = "hero-2"
  offers = "offers-2"
  mission = "mission-3"
  choose = "choose-3"
  team = "team-3"
  commitment = "commitment-3"
  hotel = "hotel-3"

# Доступні компоненти
[params.layouts.available]
  headers = ["header-1", "header-2", "header-3"]
  footers = ["footer-1", "footer-2", "footer-3"]
  heros = ["hero-1", "hero-2", "hero-3"]
  offers = ["offers-1", "offers-2", "offers-3"]
  missions = ["mission-1", "mission-2", "mission-3"]
  choose = ["choose-1", "choose-2", "choose-3"]
  teams = ["team-1", "team-2", "team-3"]
  commitments = ["commitment-1", "commitment-2", "commitment-3"]
  hotels = ["hotel-1", "hotel-2", "hotel-3"]


# Налаштування меню
[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Example hotels"
  url = "/example-hotels/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about"
  weight = 6

  [[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 7